name: ataylorme-wordpress

recipe: pantheon

config:
  framework: wordpress
  site: ataylorme-wordpress
  id: 489520a4-b156-4743-8e4c-dffdcf353fa2
  xdebug: false
  webroot: web

services:
# Spin up a PHP CI service for Behat, PHPUnit, etc.
  ci:
    type: php:custom
    run_as_root:
      - chmod 777 /tmp
      - mkdir -p /var/www/.composer/cache
      - chmod 777 /var/www/.composer/cache
    overrides:
      image: quay.io/pantheon-public/build-tools-ci:6.x
      environment:
        PANTHEON_ENVIRONMENT: lando
        # Get this info from "lando info"
        LANDO_INTERNAL_SITE_URL: https://appserver_nginx
        LANDO_URL: https://ataylorme-wordpress.lndo.site/
        DB_HOST: 'database'
        DB_PORT: 3306
        DB_USER: 'pantheon'
        DB_PASSWORD: 'pantheon'
        DB_NAME: 'pantheon'
        BEHAT_ADMIN_PASSWORD: 'running-behat-locally-ftw'
        BEHAT_ADMIN_EMAIL: 'andrew+local-ci@pantheon.io'
        BEHAT_ADMIN_USERNAME: 'pantheon-ci-testing-local'

  appserver:
    overrides:
      environment:
        PANTHEON_ENVIRONMENT: lando
        # Get this info from "lando info"
        LANDO_URL: https://ataylorme-wordpress.lndo.site/
        DB_HOST: 'database'
        DB_PORT: 3306
        DB_USER: 'pantheon'
        DB_PASSWORD: 'pantheon'
        DB_NAME: 'pantheon'
        BEHAT_ADMIN_PASSWORD: 'running-behat-locally-ftw'
        BEHAT_ADMIN_EMAIL: 'andrew+local-ci@pantheon.io'
        BEHAT_ADMIN_USERNAME: 'pantheon-ci-testing-local'

# Extra event hooks
events:
  post-pull:
    - appserver: wp search-replace 'ataylor.me' 'ataylorme-wordpress.lndo.site'
    - appserver: wp search-replace 'live-ataylorme-wordpress.pantheonsite.io' 'ataylorme-wordpress.lndo.site'
    - appserver: wp cache flush
    - appserver: sleep 5
    - appserver: wp plugin deactivate amp
    - appserver: wp theme activate ataylorme-wordpress-theme
    - appserver: ./.ci/lando/create-wp-admin-user

# Additional "lando" commands
tooling:
  composer:
    service: appserver
  wp:
    service: appserver
  unit-test:
    description: Run unit tests
    cmd: composer -n unit-test
    service: ci
  code-sniff:
    description: Run code sniffing
    cmd: composer -n code-sniff
    service: ci
  restore-db:
    description: Restore the database
    cmd: ./.ci/lando/restore-db
    service: appserver
  export-db:
    description: export the database
    cmd: ./.ci/lando/export-db
    service: appserver
  behat-commands:
    description: List Behat scenarios
    cmd: composer -n behat-scenarios
    service: ci
  delete-admin-user:
    description: Delete admin WordPress user
    cmd: ./.ci/lando/delete-wp-admin-user
    service: appserver
  create-admin-user:
    description: Create admin WordPress user
    cmd: ./.ci/lando/create-wp-admin-user
    service: appserver
  push: disabled