name: ataylorme-wordpress

recipe: pantheon

config:
  framework: wordpress
  site: ataylorme-wordpress
  id: 489520a4-b156-4743-8e4c-dffdcf353fa2
  xdebug: false
  webroot: web

services:
  # Spin up a PHP CI service for Behat, PHPUnit, etc.
  ci:
    type: php:custom
    overrides:
      image: quay.io/pantheon-public/build-tools-ci:6.x
      environment:
        PANTHEON_ENVIRONMENT: lando
        # Get this info from "lando info"
        LANDO_INTERNAL_SITE_URL: https://edge_ssl.ataylormewordpress.internal
        LANDO_URL: https://ataylorme-wordpress.lndo.site/
        DB_HOST: 'database'
        DB_PORT: 3306
        DB_USER: 'pantheon'
        DB_PASSWORD: 'pantheon'
        DB_NAME: 'pantheon'
  appserver:
    overrides:
      environment:
        PANTHEON_ENVIRONMENT: lando
        # Get this info from "lando info"
        LANDO_INTERNAL_SITE_URL: https://edge_ssl.ataylormewordpress.internal
        LANDO_URL: https://ataylorme-wordpress.lndo.site/
        DB_HOST: 'database'
        DB_PORT: 3306
        DB_USER: 'pantheon'
        DB_PASSWORD: 'pantheon'
        DB_NAME: 'pantheon'

# Additional "lando" commands
tooling:
  tmp-permissions:
    description: Temp directory permission
    cmd: 
      - chmod 777 /tmp
      - mkdir -p /var/www/.composer/cache
      - chmod 777 /var/www/.composer/cache
    service: ci
    user: root
  composer:
    service: appserver
  wp:
    service: appserver
  unit-test:
    description: Run unit tests
    cmd: composer -n unit-test
    service: ci
  code-sniff:
    description: Run code sniffing
    cmd: composer -n code-sniff
    service: ci
  restore-db:
    description: Restore the database
    cmd: ./.ci/lando/restore-db
    service: appserver
  export-db:
    description: export the database
    cmd:
      - appserver: ./.ci/lando/delete-wp-admin-user
      - appserver: ./.ci/lando/export-db
    service: appserver
  behat:
    description: Run Behat
    cmd:
      - appserver: ./.ci/lando/delete-wp-admin-user
      - appserver: ./.ci/lando/export-db "pre-behat-tests"
      - appserver: ./.ci/lando/create-wp-admin-user
      - ci: google-chrome --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --no-sandbox </dev/null &>/dev/null &
      - ci: ./.ci/lando/behat
      - ci: pkill -f "(chrome)?(--headless)"
      - appserver: ./.ci/lando/restore-db "pre-behat-tests"
  behat-commands:
    description: List Behat scenarios
    cmd: composer -n behat-scenarios
    service: ci
  delete-admin-user:
    description: Delete admin WordPress user
    cmd: ./.ci/lando/delete-wp-admin-user
    service: appserver
  create-admin-user:
    description: Create admin WordPress user
    cmd: ./.ci/lando/create-wp-admin-user
    service: appserver
  pull-live:
    description: Pull DB and files from the Pantheon live environment
    service: appserver
    cmd:
      # Files
      - rm -f /tmp/files.sql.gz
      - terminus backup:get ataylorme-wordpress.live --element=files --to=/tmp/files.tar.gz
      - mkdir -p /app/wp-content/uploads
      - tar -xzvf /tmp/files.tar.gz -C /app/wp-content/uploads --strip-components 1
      # Database
      - rm -f /tmp/database.sql.gz
      - terminus backup:get ataylorme-wordpress.live --element=db --to=/tmp/database.sql.gz
      - ./.ci/lando/restore-db "/tmp/database"
      # wp-cli cleanup
      - wp search-replace 'ataylor.me' 'ataylorme-wordpress.lndo.site'
      - wp search-replace 'live-ataylorme-wordpress.pantheonsite.io' 'ataylorme-wordpress.lndo.site'
      - wp plugin deactivate amp
      - wp theme activate ataylorme-wordpress-theme
  push: disabled
  pull: disabled