#!/bin/bash

# Set up variables
export RELOCATED_WP_ADMIN=TRUE
BEHAT_ADMIN_USERNAME="pantheon-ci-testing-local"
BEHAT_ADMIN_EMAIL="andrew+local-ci@pantheon.io"
BEHAT_ADMIN_PASSWORD="running-behat-locally-ftw"

# Export the DB prior to testing
echo -e "\nExporting the DB prior to testing..."
lando db-export pre-behat-tests

# Dynamically set Behat configuration parameters
export BEHAT_PARAMS='{"extensions":{"Behat\\MinkExtension":{"base_url":"https://ataylorme-wordpress.lndo.site/"},"PaulGibbs\\WordpressBehatExtension":{"site_url":"https://ataylorme-wordpress.lndo.site/wp","users":{"admin":{"username":"'$BEHAT_ADMIN_USERNAME'","password":"'$BEHAT_ADMIN_PASSWORD'"}},"wpcli":{"binary":"lando wp"}}}}'

# Start headless Chrome
echo -e "\nStarting headless Chrome..."
#chrome --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --no-sandbox &
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --no-sandbox </dev/null &>/dev/null &

echo -e "\nWaiting 5 seconds for Chrome to initialize..."
sleep 5

# Run Behat, excluding Pantheon only tests
echo -e "\nRunning the Behat tests..."
./vendor/bin/behat --config=tests/behat/behat-pantheon.yml --strict --colors --format-settings='{"paths": false}' --tags '~@live' --rerun || behat --rerun

# Restore the database to its state prior to testing
echo -e "\nRestoring the DB after testing..."
lando db-import pre-behat-tests.gz
rm pre-behat-tests.gz

# Stop headless Chrome
echo -e "\nStopping headless Chrome..."
pkill -f "(chrome)?(--headless)"

echo -e "\nAll done!"