#!/bin/bash

# Exit immediately on errors, and echo commands as they are executed.
set -ex

if [ -d "web/wp/wp-content/mu-plugins/" ]; then
  rsync -r web/wp/wp-content/mu-plugins/* web/wp-content/mu-plugins/
fi

if [ -f "web/wp/wp-config.php" ]; then
  rm web/wp/wp-config.php
fi

if [ -d "web/wp/wp-content" ]; then
  rm -rf web/wp/wp-content
fi


if [ -d "web/wp-content/plugins/site-kit-dev-settings/google-site-kit-dev-settings" ]; then
  mv web/wp-content/plugins/site-kit-dev-settings/google-site-kit-dev-settings/* web/wp-content/plugins/site-kit-dev-settings/
  ls web/wp-content/plugins/site-kit-dev-settings/google-site-kit-dev-settings
  rm -rf web/wp-content/plugins/site-kit-dev-settings/google-site-kit-dev-settings
  rm -rf web/wp-content/plugins/site-kit-dev-settings/__MACOSX
fi
