#!/bin/bash

if [ -z "$1" ]
then
    DB_FILE_NAME="pre-behat-tests"
else
    DB_FILE_NAME="$1"
fi

if [ ! -f "$DB_FILE_NAME.sql.gz" ]
then
    echo -e "The file $DB_FILE_NAME.sql.gz does not exists"
    exit 1
fi

# Un-gzip the backup
gunzip $DB_FILE_NAME.sql.gz

# Build the SQL prefix
SQLSTART="mysql --user=$DB_USER --host=$DB_HOST --port=$DB_PORT --password=$DB_PASSWORD $DB_NAME"

# Get all the tables
DB_TABLES=$($SQLSTART -e 'SHOW TABLES' | awk '{ print $1}' | grep -v '^Tables' )

# Drop each tables
echo -e "\nDropping all the tables in the $DB_NAME database..."
for DB_TABLE in $DB_TABLES; do
    $SQLSTART -e "DROP TABLE $DB_TABLE"
done

# Import the DB
echo -e "\nImporting the $DB_NAME database..."
cat $DB_FILE_NAME.sql | $SQLSTART

# Remove the DB export file
if [ -f $DB_FILE_NAME.sql ]
then
    echo -e "\nCleaning up the leftover $DB_FILE_NAME.sql ..."
    rm $DB_FILE_NAME.sql
fi