#!/bin/bash

if [[ ${CI_BRANCH} != "master" && -z ${PR_NUMBER} ]];
then
  echo -e "CI will only deploy to Pantheon if on the master branch or creating a pull requests.\n"
  exit 0;
fi

echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo "Behat clean up on site: $TERMINUS_SITE.$TERMINUS_ENV"
echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo

# Restore the DB backup made before testing
terminus -n backup:restore $TERMINUS_SITE.$TERMINUS_ENV --element=database --yes

# Clear site cache
terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV

# Store artifacts
export ARTIFACTS_DIR_URL="${CI_BUILD_URL}/artifacts/${CI_NODE_INDEX}/artifacts"

# Create the artifacts directory if needed
if [ ! -d "$ARTIFACTS_FULL_DIR" ]; then
  mkdir -p $ARTIFACTS_FULL_DIR
fi


# Copy behat-screenshots files to ARTIFACTS_FULL_DIR
echo -e "\nCopying behat-screenshots files to $ARTIFACTS_FULL_DIR..."
if [ -d "$ARTIFACTS_FULL_DIR/behat-screenshots" ]; then
  rm -rf $ARTIFACTS_FULL_DIR/behat-screenshots
fi

if [ -d behat-screenshots ]; then
    cp -r behat-screenshots $ARTIFACTS_FULL_DIR/
fi