#!/bin/bash

if [[ ${CI_BRANCH} != "master" && -z ${PR_NUMBER} ]];
then
  echo -e "CI will only deploy to Pantheon if on the master branch or creating a pull requests.\n"
  exit 0;
fi

# Bail if required environment varaibles are missing
if [ -z "$TERMINUS_SITE" ] || [ -z "$TERMINUS_ENV" ]
then
  echo 'No test site specified. Set TERMINUS_SITE and TERMINUS_ENV.'
  exit 1
fi

echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo "Behat test site: $TERMINUS_SITE.$TERMINUS_ENV"
echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo

# Wake the multidev environment before running tests
terminus -n env:wake $TERMINUS_SITE.$TERMINUS_ENV

# Ping wp-cli to start ssh with the app server
terminus -n wp $TERMINUS_SITE.$TERMINUS_ENV -- cli version

# Verbose mode and exit on errors
set -ex

# Start headless Chrome
echo "\n Starting Chrome in headless mode ..."
google-chrome --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --no-sandbox </dev/null &>/dev/null &

# Dynamically set Behat configuration parameters
export BEHAT_PARAMS='{"extensions": {"Behat\\MinkExtension": {"base_url": "https://'$TERMINUS_ENV'-'$TERMINUS_SITE'.pantheonsite.io"},"PaulGibbs\\WordpressBehatExtension": {"site_url": "https://'$TERMINUS_ENV'-'$TERMINUS_SITE'.pantheonsite.io/wp","users": {"admin": {"username": "'$BEHAT_ADMIN_USERNAME'","password": "'$BEHAT_ADMIN_PASSWORD'"}},"wpcli": {"binary": "terminus -n wp '$TERMINUS_SITE'.'$TERMINUS_ENV' --"}},"FailAid\\Extension": {"screenshot": {"directory": "'$CIRCLE_WORKING_DIRECTORY'/behat-screenshots/"}}}}'

# Set Behat variables from environment variables
export RELOCATED_WP_ADMIN=TRUE

# Run the Behat tests
./vendor/bin/behat --config=tests/behat/behat-pantheon.yml --strict --colors  "$@" --rerun || ./vendor/bin/behat --config=tests/behat/behat-pantheon.yml --strict --colors  "$@" --rerun
