#!/bin/bash

set -eo pipefail

cp /tmp/workspace/bash_env.txt $BASH_ENV
echo "export CI_BUILD_URL='${CIRCLE_BUILD_URL}'" >> $BASH_ENV
echo "export CI_NODE_INDEX='${CIRCLE_NODE_INDEX}'" >> $BASH_ENV
source $BASH_ENV